services:
  web:
    build: .
    container_name: django_ecommerce_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_data:/app/staticfiles 
      - media:/app/media

    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: ecommerce_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}        # Uses environment variable from Render
      POSTGRES_USER: ${POSTGRES_USER}    # Uses environment variable from Render
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Uses environment variable from Render
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_data:/home/app/static
      - media:/home/app/media
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web

volumes:
  pgdata:
  static_data:
  media:
